### ISSUE TITLE
`slf4j 2.0` (hence `aio-lib-java` `1.1.0`) is not supported by `sling`/`aem`

### ISSUE THREAD

**Issue by francoisledroff** [adobe/aio-lib-java#182]
If you are an `AEM` customer, please use a previous release.

see https://issues.apache.org/jira/browse/SLING-11906

**Comment by rombert** [comment]
From a Sling point of view it's a long way to SLF4j 2.0 compatibility because we have lots of consumers that are bound to slf4j 1.x because of their importing 'non-core' packages like `org.slf4j.event` or `org.slf4j.helpers`.

I am wondering whether this bundle really needs slf4j 2.0 or whether it works with both 1.x and 2.x and can relax its import constraints.

**Comment by bstopp** [comment]
Maybe leave the top-level slf4j dependency version to be 2.x, but the AEM sub-package parent pom overrides it downgraded to 1.x?

This way third party, non-aem uses can keep up-to-date, but the AEM bundles still deploy correctly to that context?

**Comment by francoisledroff** [comment]
closing this (should ahve done it a long time ago)
as we downgraded sl4j to support aem see https://github.com/adobe/aio-lib-java/pull/185

I created a follow up issue : https://github.com/adobe/aio-lib-java/issues/225
